### ISSUE TITLE
MVPリリース依頼

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#80]
## 各種情報
サービスの概要とMVPで検証する事柄：
 ### サービスの概要
My Song Journalは、毎日の気分に合わせて曲と一言メモを記録することで、自分だけの音楽日記を作成できるサービスです。公開設定されている場合に限り、友人が書いた日記も覗くことができるため、音楽と一言メモを通じて友人の心情や趣味をより深く知るきっかけにもなります。共通の感情や音楽の趣味をシェアすることで、自己理解にも他者理解にもつながり、より豊かな繋がりを築くことができます。

### MVPで検証する事柄
- [ ] deviseでのログインログアウト新規登録が通常に機能するか
- [ ] 日記作成ページでタイトル、ひとことメモ、感情、アーティスト名、曲名を入力できること（現状では、全て手入力かつアーティスト名と曲名は存在しないものを入れても通るようになっていますが、今回は入力ができていればいいということにしました）
- [ ] 日記の編集、削除が出来、詳細ページに飛べること
- [ ] 日記を感情ごとにしぼり込めること（感情を選択して、絞り込みを行えること）

サービス名：MySongJournal
サービスURL：https://mysongjorunal.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- **ユーザー認証機能**: ユーザー登録、ログイン、ログアウト機能
- **日記作成・一覧機能**: 気分・曲名・アーティスト名・一言メモの記録と表示
- **絞り込み機能**: 感情で絞り込んで日記を一覧表示

## READMEレビュー時から変更した機能
- **Spotify APIとの連携**: 楽曲検索や基本的な楽曲情報の取得
⇒Spotify APIとの連携は本リリースに回すことにしました。（本リリースではSpotifyAPIからアーティスト名、曲名、ジャケット写真、プレビューURLを動的にもってこれるようにする予定です）
- **シンプルな感情プレイリスト**: 感情ごとに日記を絞り込み、感情別プレイリストとして表示
⇒- **絞り込み機能**: 感情で絞り込んで日記を一覧表示と同義に思うので、今回は要件として削除しました（本リリースでレコメンド機能として、感情に見合った曲を提案する機能を実装する予定でいます）

## サービスイメージがわかるようなスクリーンショット等
TOP画面（未ログイン時）
![image](https://github.com/user-attachments/assets/71120bac-1f78-495f-94a8-39232aa95252)b8b7babf020a)
TOP画面（ログイン時）
![image](https://github.com/user-attachments/assets/fde6cfe1-e2d2-4f60-9852-de0a95b3bad6)
日記作成ページ
![image](https://github.com/user-attachments/assets/e0778dcc-44a5-4617-86fc-f2660eebfe86)
日記一覧ページ（絞り込み）
![image](https://github.com/user-attachments/assets/a8c2dd23-23eb-465d-a9dd-3a4232fa1a77)
日記詳細ページ
![image](https://github.com/user-attachments/assets/bcc291a9-08f0-42bf-907a-216308f49d74)
日記編集ページ
![image](https://github.com/user-attachments/assets/c8a55223-f5f1-46f0-a144-a45e8d50f5ab)

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
>友人が書いた日記も覗くことができる

上記の昨日は、MVPに含まれない形でしょうか？
「みんなの日記を覗きにいく」のリンクから機能を使うことができなかったので、ご確認をお願いします。

**Comment by kogoro06** [comment]
ご連絡ありがとうございます！
　記載漏れしてしまい申し訳ございません！
「みんなの日記を覗きにいく」は本リリースで実装予定です（この機能はログイン前でも利用できるようにする予定です）

**Comment by shota-hope** [comment]
返信ありがとうございます。

ヘッダーのプロフィールもMVPに含まれないのでしょうか？
その他、以下は問題ないと思います。
>  MVPで検証する事柄
deviseでのログインログアウト新規登録が通常に機能するか
 日記作成ページでタイトル、ひとことメモ、感情、アーティスト名、曲名を入力できること（現状では、全て手入力かつアーティスト名と曲名は存在しないものを入れても通るようになっていますが、今回は入力ができていればいいということにしました）
 日記の編集、削除が出来、詳細ページに飛べること
 日記を感情ごとにしぼり込めること（感情を選択して、絞り込みを行えること）

MVPリリース後でも良いですが、使用できない機能は非表示にするか、今は使えないということがユーザーにわかるようにしたほうが親切かと思いました。
ご確認よろしくお願いします。

**Comment by kogoro06** [comment]
ご連絡ありがとうございます！
そうですね、プロフィールも本リリースでの実装を予定しています

使用できない機能は非表示にするか、今は使えないということがユーザーにわかるようにしたほうが親切⇒ご指摘ありがとうございます！本リリースの実装に入る前にこの辺のまだ使用できないリンクについては非表示にしておこうと思います

MVP段階では以下のMVPで検証する事柄のみ実装してあります。

```
 deviseでのログインログアウト新規登録が通常に機能するか
 日記作成ページでタイトル、ひとことメモ、感情、アーティスト名、曲名を入力できること（現状では、全て手入力かつアーティスト名と曲名は存在しないものを入れても通るようになっていますが、今回は入力ができていればいいということにしました）
 日記の編集、削除が出来、詳細ページに飛べること
 日記を感情ごとにしぼり込めること（感情を選択して、絞り込みを行えること）
```
ご確認のほどよろしくお願いします

**Comment by shota-hope** [comment]
返信ありがとうございます。
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
